package com.delmar.sys.model;

import com.delmar.core.model.CoreModel;

/**
 * @author 刘大磊 2015年1月16日 上午8:52:41
 */
public class Org extends CoreModel {
	public static final Integer ORG_LEVEL_1=1;
	public static final Integer ORG_LEVEL_2=2;
	public static final Integer ORG_LEVEL_3=3;

    private String value;
    private String name;
    private String remark;
    private Integer orgLevel;
    private Integer parentOrgId;
    private Integer clientId;
    private Org parentOrg;
    private Client client;
    
    
    public Org()
    {
    	
    }
    
    public Org(Integer id,String name)
    {
    	this.id=id;
    	this.name=name;
    }
    /**
	 * @return the client
	 */
	public Client getClient() {
		return client;
	}

	/**
	 * @param client the client to set
	 */
	public void setClient(Client client) {
		this.client = client;
	}

	/**
	 * @return the parentOrg
	 */
	public Org getParentOrg() {
		return parentOrg;
	}

	/**
	 * @param parentOrg the parentOrg to set
	 */
	public void setParentOrg(Org parentOrg) {
		this.parentOrg = parentOrg;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.id
     *
     * @return the value of sys_org.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.id
     *
     * @param id the value for sys_org.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.value
     *
     * @return the value of sys_org.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.value
     *
     * @param value the value for sys_org.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.name
     *
     * @return the value of sys_org.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.name
     *
     * @param name the value for sys_org.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_org.remark
     *
     * @return the value of sys_org.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_org.remark
     *
     * @param remark the value for sys_org.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    public Integer getClientId() {
        return clientId;
    }

    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
	 * @return the orgLevel
	 */
	public Integer getOrgLevel() {
		return orgLevel;
	}

	/**
	 * @param orgLevel the orgLevel to set
	 */
	public void setOrgLevel(Integer orgLevel) {
		this.orgLevel = orgLevel;
	}

	/**
	 * @return the parentOrgId
	 */
	public Integer getParentOrgId() {
		return parentOrgId;
	}

	/**
	 * @param parentOrgId the parentOrgId to set
	 */
	public void setParentOrgId(Integer parentOrgId) {
		this.parentOrgId = parentOrgId;
	}
    
}