package com.delmar.core.model;

/**
 * @author 刘大磊 2014年12月18日 下午8:19:12
 * 
 * 主键映射表
 */

public class Codemapinfo extends CoreModel{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_codemapinfo.id
     *
     * @mbggenerated
     */

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_codemapinfo.maptype
     *
     * @mbggenerated
     */
    private String maptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_codemapinfo.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_codemapinfo.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_codemapinfo.mappedcode
     *
     * @mbggenerated
     */
    private String mappedcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_codemapinfo.mappedname
     *
     * @mbggenerated
     */
    private String mappedname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_codemapinfo.id
     *
     * @return the value of core_codemapinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_codemapinfo.id
     *
     * @param id the value for core_codemapinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_codemapinfo.maptype
     *
     * @return the value of core_codemapinfo.maptype
     *
     * @mbggenerated
     */
    public String getMaptype() {
        return maptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_codemapinfo.maptype
     *
     * @param maptype the value for core_codemapinfo.maptype
     *
     * @mbggenerated
     */
    public void setMaptype(String maptype) {
        this.maptype = maptype == null ? null : maptype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_codemapinfo.code
     *
     * @return the value of core_codemapinfo.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_codemapinfo.code
     *
     * @param code the value for core_codemapinfo.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_codemapinfo.name
     *
     * @return the value of core_codemapinfo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_codemapinfo.name
     *
     * @param name the value for core_codemapinfo.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_codemapinfo.mappedcode
     *
     * @return the value of core_codemapinfo.mappedcode
     *
     * @mbggenerated
     */
    public String getMappedcode() {
        return mappedcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_codemapinfo.mappedcode
     *
     * @param mappedcode the value for core_codemapinfo.mappedcode
     *
     * @mbggenerated
     */
    public void setMappedcode(String mappedcode) {
        this.mappedcode = mappedcode == null ? null : mappedcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_codemapinfo.mappedname
     *
     * @return the value of core_codemapinfo.mappedname
     *
     * @mbggenerated
     */
    public String getMappedname() {
        return mappedname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_codemapinfo.mappedname
     *
     * @param mappedname the value for core_codemapinfo.mappedname
     *
     * @mbggenerated
     */
    public void setMappedname(String mappedname) {
        this.mappedname = mappedname == null ? null : mappedname.trim();
    }
}