package com.delmar.core.model;

/**
 * @author 刘大磊 2014年12月18日 下午8:19:33
 * 
 * ID管理表
 */
public class Idrelatedinfo extends CoreModel{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_idrelatedinfo.origincode
     *
     *
     */
    private String origincode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_idrelatedinfo.originname
     *
     *
     */
    private String originname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_idrelatedinfo.relatedcode
     *
     *
     */
    private String relatedcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_idrelatedinfo.relatedname
     *
     *
     */
    private String relatedname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_idrelatedinfo.relatedtype
     *
     *
     */
    private String relatedtype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_idrelatedinfo.id
     *
     * @return the value of core_idrelatedinfo.id
     *
     *
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_idrelatedinfo.id
     *
     * @param id the value for core_idrelatedinfo.id
     *
     *
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_idrelatedinfo.origincode
     *
     * @return the value of core_idrelatedinfo.origincode
     *
     *
     */
    public String getOrigincode() {
        return origincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_idrelatedinfo.origincode
     *
     * @param origincode the value for core_idrelatedinfo.origincode
     *
     *
     */
    public void setOrigincode(String origincode) {
        this.origincode = origincode == null ? null : origincode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_idrelatedinfo.originname
     *
     * @return the value of core_idrelatedinfo.originname
     *
     *
     */
    public String getOriginname() {
        return originname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_idrelatedinfo.originname
     *
     * @param originname the value for core_idrelatedinfo.originname
     *
     *
     */
    public void setOriginname(String originname) {
        this.originname = originname == null ? null : originname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_idrelatedinfo.relatedcode
     *
     * @return the value of core_idrelatedinfo.relatedcode
     *
     *
     */
    public String getRelatedcode() {
        return relatedcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_idrelatedinfo.relatedcode
     *
     * @param relatedcode the value for core_idrelatedinfo.relatedcode
     *
     *
     */
    public void setRelatedcode(String relatedcode) {
        this.relatedcode = relatedcode == null ? null : relatedcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_idrelatedinfo.relatedname
     *
     * @return the value of core_idrelatedinfo.relatedname
     *
     *
     */
    public String getRelatedname() {
        return relatedname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_idrelatedinfo.relatedname
     *
     * @param relatedname the value for core_idrelatedinfo.relatedname
     *
     *
     */
    public void setRelatedname(String relatedname) {
        this.relatedname = relatedname == null ? null : relatedname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column core_idrelatedinfo.relatedtype
     *
     * @return the value of core_idrelatedinfo.relatedtype
     *
     *
     */
    public String getRelatedtype() {
        return relatedtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column core_idrelatedinfo.relatedtype
     *
     * @param relatedtype the value for core_idrelatedinfo.relatedtype
     *
     *
     */
    public void setRelatedtype(String relatedtype) {
        this.relatedtype = relatedtype == null ? null : relatedtype.trim();
    }
}