package com.delmar.base.model;

import com.delmar.core.model.CoreModel;

/**
 * @author 刘大磊 2014年12月22日 上午9:47:10
 */
public class Carrier extends CoreModel{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_carrier.code
     *
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_carrier.scacode
     *
     */
    private String scaccode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_carrier.cname
     *
     *
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_carrier.ename
     *
     *
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_carrier.planeocean
     *
     *
     */
    private String planeocean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_carrier.remark
     *
     *
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_carrier.id
     *
     * @return the value of base_carrier.id
     *
     *
     */
    @Override
	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_carrier.id
     *
     * @param id the value for base_carrier.id
     *
     *
     */
    @Override
	public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_carrier.code
     *
     * @return the value of base_carrier.code
     *
     *
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_carrier.code
     *
     * @param code the value for base_carrier.code
     *
     *
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_carrier.scacode
     *
     * @return the value of base_carrier.scacode
     *
     *
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_carrier.cname
     *
     * @return the value of base_carrier.cname
     *
     *
     */
    public String getCname() {
        return cname;
    }

    /**
	 * @return the scaccode
	 */
	public String getScaccode() {
		return scaccode;
	}

	/**
	 * @param scaccode the scaccode to set
	 */
	public void setScaccode(String scaccode) {
		this.scaccode = scaccode;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_carrier.cname
     *
     * @param cname the value for base_carrier.cname
     *
     *
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_carrier.ename
     *
     * @return the value of base_carrier.ename
     *
     *
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_carrier.ename
     *
     * @param ename the value for base_carrier.ename
     *
     *
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_carrier.planeocean
     *
     * @return the value of base_carrier.planeocean
     *
     *
     */
    public String getPlaneocean() {
        return planeocean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_carrier.planeocean
     *
     * @param planeocean the value for base_carrier.planeocean
     *
     *
     */
    public void setPlaneocean(String planeocean) {
        this.planeocean = planeocean == null ? null : planeocean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_carrier.remark
     *
     * @return the value of base_carrier.remark
     *
     *
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_carrier.remark
     *
     * @param remark the value for base_carrier.remark
     *
     *
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}