package com.delmar.base.model;

import java.math.BigDecimal;

import com.delmar.core.model.CoreModel;

public class Chargename extends CoreModel{


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_chargename.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_chargename.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_chargename.necessary
     *
     * @mbggenerated
     */
    private String necessary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_chargename.freighttype
     *
     * @mbggenerated
     */
    private String freighttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_chargename.remark
     *
     * @mbggenerated
     */
    private String remark;

    private BigDecimal minValue;
    /**
	 * @return the minValue
	 */
	public BigDecimal getMinValue() {
		return minValue;
	}

	/**
	 * @param minValue the minValue to set
	 */
	public void setMinValue(BigDecimal minValue) {
		this.minValue = minValue;
	}

	/**
	 * @return the maxValue
	 */
	public BigDecimal getMaxValue() {
		return maxValue;
	}

	/**
	 * @param maxValue the maxValue to set
	 */
	public void setMaxValue(BigDecimal maxValue) {
		this.maxValue = maxValue;
	}

	private BigDecimal maxValue;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_chargename.id
     *
     * @return the value of base_chargename.id
     *
     * @mbggenerated
     */
    @Override
	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_chargename.id
     *
     * @param id the value for base_chargename.id
     *
     * @mbggenerated
     */
    @Override
	public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_chargename.code
     *
     * @return the value of base_chargename.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_chargename.code
     *
     * @param code the value for base_chargename.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_chargename.name
     *
     * @return the value of base_chargename.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_chargename.name
     *
     * @param name the value for base_chargename.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_chargename.necessary
     *
     * @return the value of base_chargename.necessary
     *
     * @mbggenerated
     */
    public String getNecessary() {
        return necessary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_chargename.necessary
     *
     * @param necessary the value for base_chargename.necessary
     *
     * @mbggenerated
     */
    public void setNecessary(String necessary) {
        this.necessary = necessary == null ? null : necessary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_chargename.freighttype
     *
     * @return the value of base_chargename.freighttype
     *
     * @mbggenerated
     */
    public String getFreighttype() {
        return freighttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_chargename.freighttype
     *
     * @param freighttype the value for base_chargename.freighttype
     *
     * @mbggenerated
     */
    public void setFreighttype(String freighttype) {
        this.freighttype = freighttype == null ? null : freighttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_chargename.remark
     *
     * @return the value of base_chargename.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_chargename.remark
     *
     * @param remark the value for base_chargename.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}