package com.delmar.base.model;

import com.delmar.core.model.CoreModel;

/**
 * @author 刘大磊 2014年12月22日 上午9:45:56
 */
public class Port extends CoreModel{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_port.portcode
     *
     * @mbggenerated
     */
    private String portcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_port.portcname
     *
     * @mbggenerated
     */
    private String portcname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_port.portename
     *
     * @mbggenerated
     */
    private String portename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_port.contorycode
     *
     * @mbggenerated
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_port.planeocean
     *
     * @mbggenerated
     */
    private String planeocean;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_port.remark
     *
     * @mbggenerated
     */
    private String remark;
    
    private Integer cityId;
    /**
	 * @return the cityId
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * @param cityId the cityId to set
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_port.id
     *
     * @return the value of base_port.id
     *
     * @mbggenerated
     */
    @Override
	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_port.id
     *
     * @param id the value for base_port.id
     *
     * @mbggenerated
     */
    @Override
	public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_port.portcode
     *
     * @return the value of base_port.portcode
     *
     * @mbggenerated
     */
    public String getPortcode() {
        return portcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_port.portcode
     *
     * @param portcode the value for base_port.portcode
     *
     * @mbggenerated
     */
    public void setPortcode(String portcode) {
        this.portcode = portcode == null ? null : portcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_port.portcname
     *
     * @return the value of base_port.portcname
     *
     * @mbggenerated
     */
    public String getPortcname() {
        return portcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_port.portcname
     *
     * @param portcname the value for base_port.portcname
     *
     * @mbggenerated
     */
    public void setPortcname(String portcname) {
        this.portcname = portcname == null ? null : portcname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_port.portename
     *
     * @return the value of base_port.portename
     *
     * @mbggenerated
     */
    public String getPortename() {
        return portename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_port.portename
     *
     * @param portename the value for base_port.portename
     *
     * @mbggenerated
     */
    public void setPortename(String portename) {
        this.portename = portename == null ? null : portename.trim();
    }


    /**
	 * @return the countryCode
	 */
	public String getCountryCode() {
		return countryCode;
	}

	/**
	 * @param countryCode the countryCode to set
	 */
	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_port.planeocean
     *
     * @return the value of base_port.planeocean
     *
     * @mbggenerated
     */
    public String getPlaneocean() {
        return planeocean;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_port.planeocean
     *
     * @param planeocean the value for base_port.planeocean
     *
     * @mbggenerated
     */
    public void setPlaneocean(String planeocean) {
        this.planeocean = planeocean == null ? null : planeocean.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_port.remark
     *
     * @return the value of base_port.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_port.remark
     *
     * @param remark the value for base_port.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}