package com.delmar.base.model;

import com.delmar.core.model.CoreModel;

public class Unit extends CoreModel{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_unit.code
     *
     *
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_unit.name
     *
     *
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_unit.remark
     *
     *
     */
    private String remark;
    
    private String unitType;

    /**
	 * @return the unitType
	 */
	public String getUnitType() {
		return unitType;
	}

	/**
	 * @param unitType the unitType to set
	 */
	public void setUnitType(String unitType) {
		this.unitType = unitType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_unit.id
     *
     * @return the value of base_unit.id
     *
     *
     */
    @Override
	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_unit.id
     *
     * @param id the value for base_unit.id
     *
     *
     */
    @Override
	public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_unit.code
     *
     * @return the value of base_unit.code
     *
     *
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_unit.code
     *
     * @param code the value for base_unit.code
     *
     *
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_unit.name
     *
     * @return the value of base_unit.name
     *
     *
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_unit.name
     *
     * @param name the value for base_unit.name
     *
     *
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_unit.remark
     *
     * @return the value of base_unit.remark
     *
     *
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_unit.remark
     *
     * @param remark the value for base_unit.remark
     *
     *
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}