package com.delmar.rate.model;

import java.util.Date;

import com.delmar.core.model.CoreModel;

/**
 * @author 刘大磊 2015年2月4日 下午1:40:15
 * 主报价单信息
 */
public class Ratemaster extends CoreModel{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.rateno
     *
     *
     */
    private String rateno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.base_carrier_id
     *
     *
     */
    private Integer baseCarrierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.commondity
     *
     *
     */
    private String commondity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.pol
     *
     *
     */
    private Integer pol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.poa
     *
     *
     */
    private Integer poa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.pod
     *
     *
     */
    private Integer pod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.created
     *
     *
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.createdby
     *
     *
     */
    private Integer createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.updated
     *
     *
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.updatedby
     *
     *
     */
    private Integer updatedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.transtime
     *
     *
     */
    private Integer transtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.frequence
     *
     *
     */
    private String frequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.mode
     *
     *
     */
    private String mode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.remark
     *
     *
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.isactive
     *
     *
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_master.flag
     *
     *
     */
    private Integer flag;
    
    
    private Integer userId;
    
    private String userName;
    
    private Integer clientId;
    
    private Integer orgId;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.id
     *
     * @return the value of r_rate_master.id
     *
     *
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.id
     *
     * @param id the value for r_rate_master.id
     *
     *
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.rateno
     *
     * @return the value of r_rate_master.rateno
     *
     *
     */
    public String getRateno() {
        return rateno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.rateno
     *
     * @param rateno the value for r_rate_master.rateno
     *
     *
     */
    public void setRateno(String rateno) {
        this.rateno = rateno == null ? null : rateno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.base_carrier_id
     *
     * @return the value of r_rate_master.base_carrier_id
     *
     *
     */
    public Integer getBaseCarrierId() {
        return baseCarrierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.base_carrier_id
     *
     * @param baseCarrierId the value for r_rate_master.base_carrier_id
     *
     *
     */
    public void setBaseCarrierId(Integer baseCarrierId) {
        this.baseCarrierId = baseCarrierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.commondity
     *
     * @return the value of r_rate_master.commondity
     *
     *
     */
    public String getCommondity() {
        return commondity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.commondity
     *
     * @param commondity the value for r_rate_master.commondity
     *
     *
     */
    public void setCommondity(String commondity) {
        this.commondity = commondity == null ? null : commondity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.pol
     *
     * @return the value of r_rate_master.pol
     *
     *
     */
    public Integer getPol() {
        return pol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.pol
     *
     * @param pol the value for r_rate_master.pol
     *
     *
     */
    public void setPol(Integer pol) {
        this.pol = pol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.poa
     *
     * @return the value of r_rate_master.poa
     *
     *
     */
    public Integer getPoa() {
        return poa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.poa
     *
     * @param poa the value for r_rate_master.poa
     *
     *
     */
    public void setPoa(Integer poa) {
        this.poa = poa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.pod
     *
     * @return the value of r_rate_master.pod
     *
     *
     */
    public Integer getPod() {
        return pod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.pod
     *
     * @param pod the value for r_rate_master.pod
     *
     *
     */
    public void setPod(Integer pod) {
        this.pod = pod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.created
     *
     * @return the value of r_rate_master.created
     *
     *
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.created
     *
     * @param created the value for r_rate_master.created
     *
     *
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.createdby
     *
     * @return the value of r_rate_master.createdby
     *
     *
     */
    public Integer getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.createdby
     *
     * @param createdby the value for r_rate_master.createdby
     *
     *
     */
    public void setCreatedby(Integer createdby) {
        this.createdby = createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.updated
     *
     * @return the value of r_rate_master.updated
     *
     *
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.updated
     *
     * @param updated the value for r_rate_master.updated
     *
     *
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.updatedby
     *
     * @return the value of r_rate_master.updatedby
     *
     *
     */
    public Integer getUpdatedby() {
        return updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.updatedby
     *
     * @param updatedby the value for r_rate_master.updatedby
     *
     *
     */
    public void setUpdatedby(Integer updatedby) {
        this.updatedby = updatedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.transtime
     *
     * @return the value of r_rate_master.transtime
     *
     *
     */
    public Integer getTranstime() {
        return transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.transtime
     *
     * @param transtime the value for r_rate_master.transtime
     *
     *
     */
    public void setTranstime(Integer transtime) {
        this.transtime = transtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.frequence
     *
     * @return the value of r_rate_master.frequence
     *
     *
     */
    public String getFrequence() {
        return frequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.frequence
     *
     * @param frequence the value for r_rate_master.frequence
     *
     *
     */
    public void setFrequence(String frequence) {
        this.frequence = frequence == null ? null : frequence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.mode
     *
     * @return the value of r_rate_master.mode
     *
     *
     */
    public String getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.mode
     *
     * @param mode the value for r_rate_master.mode
     *
     *
     */
    public void setMode(String mode) {
        this.mode = mode == null ? null : mode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.remark
     *
     * @return the value of r_rate_master.remark
     *
     *
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.remark
     *
     * @param remark the value for r_rate_master.remark
     *
     *
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.isactive
     *
     * @return the value of r_rate_master.isactive
     *
     *
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.isactive
     *
     * @param isactive the value for r_rate_master.isactive
     *
     *
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_master.flag
     *
     * @return the value of r_rate_master.flag
     *
     *
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_master.flag
     *
     * @param flag the value for r_rate_master.flag
     *
     *
     */
    public void setFlag(Integer flag) {
        this.flag = flag ;
    }

	/**
	 * @return the userId
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the clientId
	 */
	public Integer getClientId() {
		return clientId;
	}

	/**
	 * @param clientId the clientId to set
	 */
	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	/**
	 * @return the orgId
	 */
	public Integer getOrgId() {
		return orgId;
	}

	/**
	 * @param orgId the orgId to set
	 */
	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}
    
}