package com.delmar.rate.model;

import java.math.BigDecimal;

import com.delmar.core.model.CoreModel;

public class Ratemarkup extends CoreModel{

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_markup.base_nameaccount_id
     *
     *
     */
    private Integer baseNameaccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_markup.r_rate_master_id
     *
     *
     */
    private Integer rRateMasterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_markup.freighttype
     *
     *
     */
    private Integer freighttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_markup.base_chargename_id
     *
     *
     */
    private Integer baseChargenameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_markup.markuptype
     *
     *
     */
    private Integer markuptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_rate_markup.markupamount
     *
     *
     */
    private BigDecimal markupamount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_markup.id
     *
     * @return the value of r_rate_markup.id
     *
     *
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_markup.id
     *
     * @param id the value for r_rate_markup.id
     *
     *
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_markup.base_nameaccount_id
     *
     * @return the value of r_rate_markup.base_nameaccount_id
     *
     *
     */
    public Integer getBaseNameaccountId() {
        return baseNameaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_markup.base_nameaccount_id
     *
     * @param baseNameaccountId the value for r_rate_markup.base_nameaccount_id
     *
     *
     */
    public void setBaseNameaccountId(Integer baseNameaccountId) {
        this.baseNameaccountId = baseNameaccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_markup.r_rate_master_id
     *
     * @return the value of r_rate_markup.r_rate_master_id
     *
     *
     */
    public Integer getrRateMasterId() {
        return rRateMasterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_markup.r_rate_master_id
     *
     * @param rRateMasterId the value for r_rate_markup.r_rate_master_id
     *
     *
     */
    public void setrRateMasterId(Integer rRateMasterId) {
        this.rRateMasterId = rRateMasterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_markup.freighttype
     *
     * @return the value of r_rate_markup.freighttype
     *
     *
     */
    public Integer getFreighttype() {
        return freighttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_markup.freighttype
     *
     * @param freighttype the value for r_rate_markup.freighttype
     *
     *
     */
    public void setFreighttype(Integer freighttype) {
        this.freighttype = freighttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_markup.base_chargename_id
     *
     * @return the value of r_rate_markup.base_chargename_id
     *
     *
     */
    public Integer getBaseChargenameId() {
        return baseChargenameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_markup.base_chargename_id
     *
     * @param baseChargenameId the value for r_rate_markup.base_chargename_id
     *
     *
     */
    public void setBaseChargenameId(Integer baseChargenameId) {
        this.baseChargenameId = baseChargenameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_markup.markuptype
     *
     * @return the value of r_rate_markup.markuptype
     *
     *
     */
    public Integer getMarkuptype() {
        return markuptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_markup.markuptype
     *
     * @param markuptype the value for r_rate_markup.markuptype
     *
     *
     */
    public void setMarkuptype(Integer markuptype) {
        this.markuptype = markuptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_rate_markup.markupamount
     *
     * @return the value of r_rate_markup.markupamount
     *
     *
     */
    public BigDecimal getMarkupamount() {
        return markupamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_rate_markup.markupamount
     *
     * @param markupamount the value for r_rate_markup.markupamount
     *
     *
     */
    public void setMarkupamount(BigDecimal markupamount) {
        this.markupamount = markupamount;
    }
}